### ISSUE TITLE
Lack documentation..

### ISSUE THREAD

**Issue by Leedehai** [danrugeles/EBNF_visualization#1]
Hi, I think this project is great but lacks instructions on how to use it..
I opened the html/index.html file in my browser, but it doesn't work. My browser keeps prompting dialogs.
![image](https://user-images.githubusercontent.com/18319900/27427288-4bc2c97c-56f3-11e7-94b7-c4be36834c8a.png)
![image](https://user-images.githubusercontent.com/18319900/27427291-50240f26-56f3-11e7-900d-a95ae52b881c.png)
And finally, a blank page with unresponsive buttons..
![image](https://user-images.githubusercontent.com/18319900/27427328-70f2c256-56f3-11e7-8301-df0dcaac86a5.png)
Thanks.

**Comment by danrugeles** [comment]
@Leedehai, 
The code was not running due to a broken dependency calling jquery library.
I have updated the code and the repo so that everything should be clear.

**Comment by Leedehai** [comment]
Thanks, appreciate it!
